<?php

// questo array contiene i dati che voglio scrivere nel mio DB per popolare la tabella 'apartments'
return [
    'apt_table' => [
        ['user_id' => 1,
        'title' => "Luminoso e nel cuore di Torino",
        'state' => 'Italy',
        'city' => "Torino",
        'street' => "Via Principe Tommaso",
        'number' => 30,
        'zip' => "10125",
        'lat' => 45.056540,
        'lon' => 7.680600,
        'views' => 154],

        ['user_id' => 4,
        'title' => "Monolocale completo luminoso",
        'state' => 'Italy',
        'city' => "Sesto San Giovanni",
        'street' => "Via Lombardia",
        'number' => 11,
        'zip' => "20099",
        'lat' => 45.520243,
        'lon' => 9.243068,
        'views' => 1087],

        ['user_id' => 3,
        'title' => "Borgomisto's House",
        'state' => 'Italy',
        'city' => "Cinesello Balsamo",
        'street' => "Via Fabio Filzi",
        'number' => 34,
        'zip' => "20092",
        'lat' => 45.551795,
        'lon' => 9.214601,
        'views' => 439],

        ['user_id' => 5,
        'title' => "Appartamento luminoso con ampio terrazzo",
        'state' => 'Italy',
        'city' => 'Cologno Monzese',
        'street' => "Via Monte Bianco",
        'number' => 5,
        'zip' => "20093",
        'lat' => 45.529194,
        'lon' => 9.273008,
        'views' => 1250],

        ['user_id' => 7,
        'title' => "Piccolo app.to nel cuore dell'Isola a Milano",
        'state' => 'Italy',
        'city' => 'Milano',
        'street' => "Via Angelo della Pergola",
        'number' => 5,
        'zip' => "20159",
        'lat' => 45.487914,
        'lon' => 9.188651,
        'views' => 1446],

        ['user_id' => 2,
        'title' => "Navigli studio flat with air conditioning",
        'state' => 'Italy',
        'city' => "Milano",
        'street' => "Via Ludovico Il Moro",
        'number' => 13,
        'zip' => "20143",
        'lat' => 45.447179,
        'lon' => 9.154118,
        'views' => 2543],

        ['user_id' => 6,
        'title' => "Parsifal Apartment",
        'state' => 'Italy',
        'city' => 'Milano',
        'street' => "Via Nicola Palmieri",
        'number' => 19,
        'zip' => "20141",
        'lat' => 45.435089,
        'lon' => 9.178374,
        'views' => 129],

        ['user_id' => 8,
        'title' => "MYNAPOLI HOME",
        'state' => 'Italy',
        'city' => "Milano",
        'street' => "Via San Maurilio",
        'number' => 4,
        'zip' => "20123",
        'lat' => 45.474069,
        'lon' => 9.185691,
        'views' => 127],

        ['user_id' => 9,
        'title' => "Terrazzi Panoramici, Corso Principale, Ascensore",
        'state' => 'Italy',
        'city' => "Napoli",
        'street' => "Via Toledo",
        'number' => 278,
        'zip' => "80132",
        'lat' => 40.839379,
        'lon' => 14.248305,
        'views' => 865],

        ['user_id' => 10,
        'title' => "Montesanto group Capri house",
        'state' => 'Italy',
        'city' => "Napoli",
        'street' => "Salita Tarsia",
        'number' => 136,
        'zip' => "80135",
        'lat' => 40.848481,
        'lon' => 14.246427,
        'views' => 1288],

        ['user_id' => 8,
        'title' => "Stanza matrimoniale in pieno centro a Genova",
        'state' => 'Italy',
        'city' => "Genova",
        'street' => "Via Galeazzo Alessi",
        'number' => 1,
        'zip' => "16128",
        'lat' => 44.402848,
        'lon' => 8.938595,
        'views' => 962],

        ['user_id' => 9,
        'title' => "Ampio locale sul lungomare",
        'state' => 'Italy',
        'city' => "Camogli",
        'street' => "Via della Repubblica",
        'number' => 96,
        'zip' => "16032",
        'lat' => 44.350511,
        'lon' => 9.153431,
        'views' => 2590],

        ['user_id' => 6,
        'title' => "Casa di Claudio",
        'state' => 'Italy',
        'city' => "Portofino",
        'street' => "Via Roma",
        'number' => 2,
        'zip' => "16034",
        'lat' => 44.303267,
        'lon' => 9.209150,
        'views' => 852],

        ['user_id' => 7,
        'title' => "Centralissimo a Bologna",
        'state' => 'Italy',
        'city' => "Bologna",
        'street' => "Via dell'Indipendenza",
        'number' => 67,
        'zip' => "40121",
        'lat' => 44.501319,
        'lon' => 11.344726,
        'views' => 1503],

        ['user_id' => 5,
        'title' => "I portici di via Piella",
        'state' => 'Italy',
        'city' => "Bologna",
        'street' => "Via Piella",
        'number' => 12,
        'zip' => "40126",
        'lat' => 44.498679,
        'lon' =>  11.345215,
        'views' => 1574],

        ['user_id' => 4,
        'title' => "Downtown Loft",
        'state' => 'Italy',
        'city' => "Bologna",
        'street' => "Via Galliera",
        'number' => 8,
        'zip' => "40121",
        'lat' => 44.497853,
        'lon' =>  11.341870,
        'views' => 156],

        ['user_id' => 3,
        'title' => "Appartamento di charme con patio a pochi passi dal Duomo",
        'state' => 'Italy',
        'city' => "Firenze",
        'street' => "Via Ferdinando Zanetti",
        'number' => 8,
        'zip' => "50123",
        'lat' => 43.773905,
        'lon' =>  11.253567,
        'views' => 3424],

        ['user_id' => 2,
        'title' => "Loft con terrazza in Santo Spirito",
        'state' => 'Italy',
        'city' => "Firenze",
        'street' => "Via Maggio",
        'number' => 4,
        'zip' => "50125",
        'lat' => 43.768071,
        'lon' => 11.249343,
        'views' => 4230],

        ['user_id' => 1,
        'title' => "Apartment Florence City Centre",
        'state' => 'Italy',
        'city' => "Firenze",
        'street' => "Via dei Servi",
        'number' => 7,
        'zip' => "50122",
        'lat' => 43.774551,
        'lon' => 11.258192,
        'views' => 1201],

        ['user_id' => 7,
        'title' => "Suite Leonardo",
        'state' => 'Italy',
        'city' => "Roma",
        'street' => "Via Napoli",
        'number' => 54,
        'zip' => "00184",
        'lat' => 41.901500,
        'lon' => 12.493430,
        'views' => 983],

        ['user_id' => 5,
        'title' => "Loft Garden San Lorenzo",
        'state' => 'Italy',
        'city' => "Roma",
        'street' => "Via dei Reti",
        'number' => 7,
        'zip' => "00185",
        'lat' => 41.899719,
        'lon' => 12.517550,
        'views' => 3547],

        ['user_id' => 4,
        'title' => "Appartamento elegante e centrale",
        'state' => 'Italy',
        'city' => "Roma",
        'street' => "Via Sciacca",
        'number' => 9,
        'zip' => "00182",
        'lat' => 41.883839,
        'lon' => 12.513824,
        'views' => 2587],

        ['user_id' => 9,
        'title' => "Casa Colosseum",
        'state' => 'Italy',
        'city' => "Roma",
        'street' => "Via Quattro Novembre",
        'number' => 157,
        'zip' => "00187",
        'lat' => 41.896850,
        'lon' => 12.486789,
        'views' => 2573],

        ['user_id' => 10,
        'title' => "Solo il cuore nel cuore di Lecce B&B familiare",
        'state' => 'Italy',
        'city' => "Lecce",
        'street' => "Via del Palazzo dei Conti",
        'number' => 12,
        'zip' => "73100",
        'lat' => 40.350947,
        'lon' => 18.169952,
        'views' => 1254],

        ['user_id' => 5,
        'title' => "La Suite del Duca",
        'state' => 'Italy',
        'city' => "Lecce",
        'street' => "Via Duca D'Aosta",
        'number' => 46,
        'zip' => "73100",
        'lat' => 40.357278,
        'lon' =>  18.177448,
        'views' => 1549],

        ['user_id' => 10,
        'title' => "Nel cuore dei Sassi - grazioso monolocale",
        'state' => 'Italy',
        'city' => "Matera",
        'street' => "Via Fiorentini",
        'number' => 71,
        'zip' => "75100",
        'lat' => 40.666673,
        'lon' => 16.608298,
        'views' => 3511],

        ['user_id' => 2,
        'title' => "Rialto Design Suite",
        'state' => 'Italy',
        'city' => "Venezia",
        'street' => "Calle del Gambaro",
        'number' => 528,
        'zip' => "30125",
        'lat' => 45.438006,
        'lon' => 12.335293,
        'views' => 6548],

        ['user_id' => 1,
        'title' => "La Casa Perfetta nel Posto Perfetto",
        'state' => 'Italy',
        'city' => "Palermo",
        'street' => "Via Giuseppe la Masa",
        'number' => 90,
        'zip' => "90139",
        'lat' => 38.127264,
        'lon' => 13.360366,
        'views' => 2411],

        ['user_id' => 1,
        'title' => "Splendida Suite al centro storico",
        'state' => 'Italy',
        'city' => "Alghero",
        'street' => "Via Cavour",
        'number' => 18,
        'zip' => "07041",
        'lat' => 40.558816,
        'lon' => 8.312007,
        'views' => 2108],

        ['user_id' => 8,
        'title' => "Vivi La Maddalena-Apartment",
        'state' => 'Italy',
        'city' => "La Maddalena",
        'street' => "Via Giuseppe Mazzini",
        'number' => 1,
        'zip' => "07024",
        'lat' => 41.212272,
        'lon' => 9.406211,
        'views' => 2587]
    ]
]
?>
